// config.bin - 01:45:41 05/08/21, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class extDB3 {
		projectName = "extDB3";
		author = "Torndeco";
		version = 1.031;
		requiredAddons[] = {};
		units[] = {};
		weapons[] = {};
	};
};

class CfgFunctions {
	class extDB3 {
		class system {
			file = "extDB3\system";
			
			class preInit {
				preInit = 1;
			};
		};
	};
};
